// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/perftestapp/model/protobuf/zoo.proto

package com.alexshabanov.perftest.serialization.model.protobuf;

import com.google.protobuf.AbstractMessage;

public final class Pb {
  private Pb() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MemoOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated string lines = 1;
    java.util.List<String> getLinesList();
    int getLinesCount();
    String getLines(int index);
    
    // required int32 count = 2;
    boolean hasCount();
    int getCount();
  }
  public static final class Memo extends
      com.google.protobuf.GeneratedMessage
      implements MemoOrBuilder {
    // Use Memo.newBuilder() to construct.
    private Memo(Builder builder) {
      super(builder);
    }
    private Memo(boolean noInit) {}
    
    private static final Memo defaultInstance;
    public static Memo getDefaultInstance() {
      return defaultInstance;
    }
    
    public Memo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Pb.internal_static_Memo_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Pb.internal_static_Memo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // repeated string lines = 1;
    public static final int LINES_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList lines_;
    public java.util.List<String>
        getLinesList() {
      return lines_;
    }
    public int getLinesCount() {
      return lines_.size();
    }
    public String getLines(int index) {
      return lines_.get(index);
    }
    
    // required int32 count = 2;
    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    public boolean hasCount() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getCount() {
      return count_;
    }
    
    private void initFields() {
      lines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      count_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCount()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < lines_.size(); i++) {
        output.writeBytes(1, lines_.getByteString(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(2, count_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < lines_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(lines_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getLinesList().size();
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Memo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Memo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Memo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Memo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Memo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Memo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Memo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Memo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Memo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Memo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Memo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements MemoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Pb.internal_static_Memo_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Pb.internal_static_Memo_fieldAccessorTable;
      }
      
      // Construct using Pb.Memo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        lines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        count_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Memo.getDescriptor();
      }
      
      public Memo getDefaultInstanceForType() {
        return Memo.getDefaultInstance();
      }
      
      public Memo build() {
        Memo result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Memo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Memo result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(
                  result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Memo buildPartial() {
        Memo result = new Memo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          lines_ = new com.google.protobuf.UnmodifiableLazyStringList(
              lines_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.lines_ = lines_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        result.count_ = count_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Memo) {
          return mergeFrom((Memo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Memo other) {
        if (other == Memo.getDefaultInstance()) return this;
        if (!other.lines_.isEmpty()) {
          if (lines_.isEmpty()) {
            lines_ = other.lines_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureLinesIsMutable();
            lines_.addAll(other.lines_);
          }
          onChanged();
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCount()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              ensureLinesIsMutable();
              lines_.add(input.readBytes());
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              count_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated string lines = 1;
      private com.google.protobuf.LazyStringList lines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureLinesIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          lines_ = new com.google.protobuf.LazyStringArrayList(lines_);
          bitField0_ |= 0x00000001;
         }
      }
      public java.util.List<String>
          getLinesList() {
        return java.util.Collections.unmodifiableList(lines_);
      }
      public int getLinesCount() {
        return lines_.size();
      }
      public String getLines(int index) {
        return lines_.get(index);
      }
      public Builder setLines(
          int index, String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinesIsMutable();
        lines_.set(index, value);
        onChanged();
        return this;
      }
      public Builder addLines(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureLinesIsMutable();
        lines_.add(value);
        onChanged();
        return this;
      }
      public Builder addAllLines(
          Iterable<String> values) {
        ensureLinesIsMutable();
        super.addAll(values, lines_);
        onChanged();
        return this;
      }
      public Builder clearLines() {
        lines_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      void addLines(com.google.protobuf.ByteString value) {
        ensureLinesIsMutable();
        lines_.add(value);
        onChanged();
      }
      
      // required int32 count = 2;
      private int count_ ;
      public boolean hasCount() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public int getCount() {
        return count_;
      }
      public Builder setCount(int value) {
        bitField0_ |= 0x00000002;
        count_ = value;
        onChanged();
        return this;
      }
      public Builder clearCount() {
        bitField0_ = (bitField0_ & ~0x00000002);
        count_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Memo)
    }
    
    static {
      defaultInstance = new Memo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Memo)
  }
  
  public interface DescriptionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string note = 1;
    boolean hasNote();
    String getNote();
    
    // required int64 timestamp = 2;
    boolean hasTimestamp();
    long getTimestamp();
    
    // required .Memo memo = 3;
    boolean hasMemo();
    Memo getMemo();
    MemoOrBuilder getMemoOrBuilder();
  }
  public static final class Description extends
      com.google.protobuf.GeneratedMessage
      implements DescriptionOrBuilder {
    // Use Description.newBuilder() to construct.
    private Description(Builder builder) {
      super(builder);
    }
    private Description(boolean noInit) {}
    
    private static final Description defaultInstance;
    public static Description getDefaultInstance() {
      return defaultInstance;
    }
    
    public Description getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Pb.internal_static_Description_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Pb.internal_static_Description_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string note = 1;
    public static final int NOTE_FIELD_NUMBER = 1;
    private Object note_;
    public boolean hasNote() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getNote() {
      Object ref = note_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          note_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNoteBytes() {
      Object ref = note_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        note_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required int64 timestamp = 2;
    public static final int TIMESTAMP_FIELD_NUMBER = 2;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // required .Memo memo = 3;
    public static final int MEMO_FIELD_NUMBER = 3;
    private Memo memo_;
    public boolean hasMemo() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public Memo getMemo() {
      return memo_;
    }
    public MemoOrBuilder getMemoOrBuilder() {
      return memo_;
    }
    
    private void initFields() {
      note_ = "";
      timestamp_ = 0L;
      memo_ = Memo.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasNote()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTimestamp()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMemo()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getMemo().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNoteBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, memo_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNoteBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, timestamp_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, memo_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Description parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Description parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Description parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Description parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Description parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Description parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Description parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Description parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Description parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Description parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Description prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements DescriptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Pb.internal_static_Description_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Pb.internal_static_Description_fieldAccessorTable;
      }
      
      // Construct using Pb.Description.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMemoFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        note_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (memoBuilder_ == null) {
          memo_ = Memo.getDefaultInstance();
        } else {
          memoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Description.getDescriptor();
      }
      
      public Description getDefaultInstanceForType() {
        return Description.getDefaultInstance();
      }
      
      public Description build() {
        Description result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Description buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Description result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(
                  result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Description buildPartial() {
        Description result = new Description(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.note_ = note_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (memoBuilder_ == null) {
          result.memo_ = memo_;
        } else {
          result.memo_ = memoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Description) {
          return mergeFrom((Description)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Description other) {
        if (other == Description.getDefaultInstance()) return this;
        if (other.hasNote()) {
          setNote(other.getNote());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasMemo()) {
          mergeMemo(other.getMemo());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasNote()) {
          
          return false;
        }
        if (!hasTimestamp()) {
          
          return false;
        }
        if (!hasMemo()) {
          
          return false;
        }
        if (!getMemo().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              note_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              timestamp_ = input.readInt64();
              break;
            }
            case 26: {
              Memo.Builder subBuilder = Memo.newBuilder();
              if (hasMemo()) {
                subBuilder.mergeFrom(getMemo());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMemo(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string note = 1;
      private Object note_ = "";
      public boolean hasNote() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getNote() {
        Object ref = note_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          note_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setNote(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        note_ = value;
        onChanged();
        return this;
      }
      public Builder clearNote() {
        bitField0_ = (bitField0_ & ~0x00000001);
        note_ = getDefaultInstance().getNote();
        onChanged();
        return this;
      }
      void setNote(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        note_ = value;
        onChanged();
      }
      
      // required int64 timestamp = 2;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000002;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // required .Memo memo = 3;
      private Memo memo_ = Memo.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Memo, Memo.Builder, MemoOrBuilder> memoBuilder_;
      public boolean hasMemo() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public Memo getMemo() {
        if (memoBuilder_ == null) {
          return memo_;
        } else {
          return memoBuilder_.getMessage();
        }
      }
      public Builder setMemo(Memo value) {
        if (memoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          memo_ = value;
          onChanged();
        } else {
          memoBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setMemo(
          Memo.Builder builderForValue) {
        if (memoBuilder_ == null) {
          memo_ = builderForValue.build();
          onChanged();
        } else {
          memoBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeMemo(Memo value) {
        if (memoBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              memo_ != Memo.getDefaultInstance()) {
            memo_ =
              Memo.newBuilder(memo_).mergeFrom(value).buildPartial();
          } else {
            memo_ = value;
          }
          onChanged();
        } else {
          memoBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearMemo() {
        if (memoBuilder_ == null) {
          memo_ = Memo.getDefaultInstance();
          onChanged();
        } else {
          memoBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public Memo.Builder getMemoBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getMemoFieldBuilder().getBuilder();
      }
      public MemoOrBuilder getMemoOrBuilder() {
        if (memoBuilder_ != null) {
          return memoBuilder_.getMessageOrBuilder();
        } else {
          return memo_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Memo, Memo.Builder, MemoOrBuilder>
          getMemoFieldBuilder() {
        if (memoBuilder_ == null) {
          memoBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Memo, Memo.Builder, MemoOrBuilder>(
                  memo_,
                  getParentForChildren(),
                  isClean());
          memo_ = null;
        }
        return memoBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Description)
    }
    
    static {
      defaultInstance = new Description(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Description)
  }
  
  public interface AnimalOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required int64 id = 1;
    boolean hasId();
    long getId();
    
    // required string name = 2;
    boolean hasName();
    String getName();
    
    // required .Description description = 3;
    boolean hasDescription();
    Description getDescription();
    DescriptionOrBuilder getDescriptionOrBuilder();
    
    // required int32 type = 4;
    boolean hasType();
    int getType();
  }
  public static final class Animal extends
      com.google.protobuf.GeneratedMessage
      implements AnimalOrBuilder {
    // Use Animal.newBuilder() to construct.
    private Animal(Builder builder) {
      super(builder);
    }
    private Animal(boolean noInit) {}
    
    private static final Animal defaultInstance;
    public static Animal getDefaultInstance() {
      return defaultInstance;
    }
    
    public Animal getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Pb.internal_static_Animal_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Pb.internal_static_Animal_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required int64 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public long getId() {
      return id_;
    }
    
    // required string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // required .Description description = 3;
    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    private Description description_;
    public boolean hasDescription() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public Description getDescription() {
      return description_;
    }
    public DescriptionOrBuilder getDescriptionOrBuilder() {
      return description_;
    }
    
    // required int32 type = 4;
    public static final int TYPE_FIELD_NUMBER = 4;
    private int type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getType() {
      return type_;
    }
    
    private void initFields() {
      id_ = 0L;
      name_ = "";
      description_ = Description.getDefaultInstance();
      type_ = 0;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDescription()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getDescription().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, description_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, type_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, description_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, type_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Animal parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Animal parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Animal parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Animal parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Animal parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Animal parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Animal parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Animal parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Animal parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Animal parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Animal prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements AnimalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Pb.internal_static_Animal_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Pb.internal_static_Animal_fieldAccessorTable;
      }
      
      // Construct using Pb.Animal.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getDescriptionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (descriptionBuilder_ == null) {
          description_ = Description.getDefaultInstance();
        } else {
          descriptionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Animal.getDescriptor();
      }
      
      public Animal getDefaultInstanceForType() {
        return Animal.getDefaultInstance();
      }
      
      public Animal build() {
        Animal result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Animal buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Animal result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(
                  result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Animal buildPartial() {
        Animal result = new Animal(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (descriptionBuilder_ == null) {
          result.description_ = description_;
        } else {
          result.description_ = descriptionBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Animal) {
          return mergeFrom((Animal)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Animal other) {
        if (other == Animal.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasDescription()) {
          mergeDescription(other.getDescription());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasDescription()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        if (!getDescription().isInitialized()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              name_ = input.readBytes();
              break;
            }
            case 26: {
              Description.Builder subBuilder = Description.newBuilder();
              if (hasDescription()) {
                subBuilder.mergeFrom(getDescription());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDescription(subBuilder.buildPartial());
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              type_ = input.readInt32();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required int64 id = 1;
      private long id_ ;
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public long getId() {
        return id_;
      }
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }
      
      // required string name = 2;
      private Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
      }
      
      // required .Description description = 3;
      private Description description_ = Description.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          Description, Description.Builder, DescriptionOrBuilder> descriptionBuilder_;
      public boolean hasDescription() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public Description getDescription() {
        if (descriptionBuilder_ == null) {
          return description_;
        } else {
          return descriptionBuilder_.getMessage();
        }
      }
      public Builder setDescription(Description value) {
        if (descriptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          description_ = value;
          onChanged();
        } else {
          descriptionBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder setDescription(
          Description.Builder builderForValue) {
        if (descriptionBuilder_ == null) {
          description_ = builderForValue.build();
          onChanged();
        } else {
          descriptionBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder mergeDescription(Description value) {
        if (descriptionBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              description_ != Description.getDefaultInstance()) {
            description_ =
              Description.newBuilder(description_).mergeFrom(value).buildPartial();
          } else {
            description_ = value;
          }
          onChanged();
        } else {
          descriptionBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      public Builder clearDescription() {
        if (descriptionBuilder_ == null) {
          description_ = Description.getDefaultInstance();
          onChanged();
        } else {
          descriptionBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      public Description.Builder getDescriptionBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getDescriptionFieldBuilder().getBuilder();
      }
      public DescriptionOrBuilder getDescriptionOrBuilder() {
        if (descriptionBuilder_ != null) {
          return descriptionBuilder_.getMessageOrBuilder();
        } else {
          return description_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          Description, Description.Builder, DescriptionOrBuilder>
          getDescriptionFieldBuilder() {
        if (descriptionBuilder_ == null) {
          descriptionBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              Description, Description.Builder, DescriptionOrBuilder>(
                  description_,
                  getParentForChildren(),
                  isClean());
          description_ = null;
        }
        return descriptionBuilder_;
      }
      
      // required int32 type = 4;
      private int type_ ;
      public boolean hasType() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getType() {
        return type_;
      }
      public Builder setType(int value) {
        bitField0_ |= 0x00000008;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000008);
        type_ = 0;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:Animal)
    }
    
    static {
      defaultInstance = new Animal(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Animal)
  }
  
  public interface ZooOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required string name = 1;
    boolean hasName();
    String getName();
    
    // repeated .Animal animals = 2;
    java.util.List<Animal>
        getAnimalsList();
    Animal getAnimals(int index);
    int getAnimalsCount();
    java.util.List<? extends AnimalOrBuilder>
        getAnimalsOrBuilderList();
    AnimalOrBuilder getAnimalsOrBuilder(
        int index);
  }
  public static final class Zoo extends
      com.google.protobuf.GeneratedMessage
      implements ZooOrBuilder {
    // Use Zoo.newBuilder() to construct.
    private Zoo(Builder builder) {
      super(builder);
    }
    private Zoo(boolean noInit) {}
    
    private static final Zoo defaultInstance;
    public static Zoo getDefaultInstance() {
      return defaultInstance;
    }
    
    public Zoo getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Pb.internal_static_Zoo_descriptor;
    }
    
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Pb.internal_static_Zoo_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // repeated .Animal animals = 2;
    public static final int ANIMALS_FIELD_NUMBER = 2;
    private java.util.List<Animal> animals_;
    public java.util.List<Animal> getAnimalsList() {
      return animals_;
    }
    public java.util.List<? extends AnimalOrBuilder>
        getAnimalsOrBuilderList() {
      return animals_;
    }
    public int getAnimalsCount() {
      return animals_.size();
    }
    public Animal getAnimals(int index) {
      return animals_.get(index);
    }
    public AnimalOrBuilder getAnimalsOrBuilder(
        int index) {
      return animals_.get(index);
    }
    
    private void initFields() {
      name_ = "";
      animals_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getAnimalsCount(); i++) {
        if (!getAnimals(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      for (int i = 0; i < animals_.size(); i++) {
        output.writeMessage(2, animals_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      for (int i = 0; i < animals_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, animals_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static Zoo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Zoo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Zoo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static Zoo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static Zoo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Zoo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static Zoo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Zoo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static Zoo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static Zoo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Zoo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements ZooOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Pb.internal_static_Zoo_descriptor;
      }
      
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Pb.internal_static_Zoo_fieldAccessorTable;
      }
      
      // Construct using Pb.Zoo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getAnimalsFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (animalsBuilder_ == null) {
          animals_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          animalsBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Zoo.getDescriptor();
      }
      
      public Zoo getDefaultInstanceForType() {
        return Zoo.getDefaultInstance();
      }
      
      public Zoo build() {
        Zoo result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(result);
        }
        return result;
      }
      
      private Zoo buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        Zoo result = buildPartial();
        if (!result.isInitialized()) {
          throw AbstractMessage.Builder.newUninitializedMessageException(
                  result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public Zoo buildPartial() {
        Zoo result = new Zoo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (animalsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            animals_ = java.util.Collections.unmodifiableList(animals_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.animals_ = animals_;
        } else {
          result.animals_ = animalsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Zoo) {
          return mergeFrom((Zoo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(Zoo other) {
        if (other == Zoo.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (animalsBuilder_ == null) {
          if (!other.animals_.isEmpty()) {
            if (animals_.isEmpty()) {
              animals_ = other.animals_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureAnimalsIsMutable();
              animals_.addAll(other.animals_);
            }
            onChanged();
          }
        } else {
          if (!other.animals_.isEmpty()) {
            if (animalsBuilder_.isEmpty()) {
              animalsBuilder_.dispose();
              animalsBuilder_ = null;
              animals_ = other.animals_;
              bitField0_ = (bitField0_ & ~0x00000002);
              animalsBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getAnimalsFieldBuilder() : null;
            } else {
              animalsBuilder_.addAllMessages(other.animals_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        for (int i = 0; i < getAnimalsCount(); i++) {
          if (!getAnimals(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              Animal.Builder subBuilder = Animal.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addAnimals(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required string name = 1;
      private Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // repeated .Animal animals = 2;
      private java.util.List<Animal> animals_ =
        java.util.Collections.emptyList();
      private void ensureAnimalsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          animals_ = new java.util.ArrayList<Animal>(animals_);
          bitField0_ |= 0x00000002;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          Animal, Animal.Builder, AnimalOrBuilder> animalsBuilder_;
      
      public java.util.List<Animal> getAnimalsList() {
        if (animalsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(animals_);
        } else {
          return animalsBuilder_.getMessageList();
        }
      }
      public int getAnimalsCount() {
        if (animalsBuilder_ == null) {
          return animals_.size();
        } else {
          return animalsBuilder_.getCount();
        }
      }
      public Animal getAnimals(int index) {
        if (animalsBuilder_ == null) {
          return animals_.get(index);
        } else {
          return animalsBuilder_.getMessage(index);
        }
      }
      public Builder setAnimals(
          int index, Animal value) {
        if (animalsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnimalsIsMutable();
          animals_.set(index, value);
          onChanged();
        } else {
          animalsBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setAnimals(
          int index, Animal.Builder builderForValue) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          animals_.set(index, builderForValue.build());
          onChanged();
        } else {
          animalsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAnimals(Animal value) {
        if (animalsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnimalsIsMutable();
          animals_.add(value);
          onChanged();
        } else {
          animalsBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addAnimals(
          int index, Animal value) {
        if (animalsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureAnimalsIsMutable();
          animals_.add(index, value);
          onChanged();
        } else {
          animalsBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addAnimals(
          Animal.Builder builderForValue) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          animals_.add(builderForValue.build());
          onChanged();
        } else {
          animalsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addAnimals(
          int index, Animal.Builder builderForValue) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          animals_.add(index, builderForValue.build());
          onChanged();
        } else {
          animalsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllAnimals(
          Iterable<? extends Animal> values) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          super.addAll(values, animals_);
          onChanged();
        } else {
          animalsBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearAnimals() {
        if (animalsBuilder_ == null) {
          animals_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          animalsBuilder_.clear();
        }
        return this;
      }
      public Builder removeAnimals(int index) {
        if (animalsBuilder_ == null) {
          ensureAnimalsIsMutable();
          animals_.remove(index);
          onChanged();
        } else {
          animalsBuilder_.remove(index);
        }
        return this;
      }
      public Animal.Builder getAnimalsBuilder(
          int index) {
        return getAnimalsFieldBuilder().getBuilder(index);
      }
      public AnimalOrBuilder getAnimalsOrBuilder(
          int index) {
        if (animalsBuilder_ == null) {
          return animals_.get(index);  } else {
          return animalsBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends AnimalOrBuilder>
           getAnimalsOrBuilderList() {
        if (animalsBuilder_ != null) {
          return animalsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(animals_);
        }
      }
      public Animal.Builder addAnimalsBuilder() {
        return getAnimalsFieldBuilder().addBuilder(
            Animal.getDefaultInstance());
      }
      public Animal.Builder addAnimalsBuilder(
          int index) {
        return getAnimalsFieldBuilder().addBuilder(
            index, Animal.getDefaultInstance());
      }
      public java.util.List<Animal.Builder>
           getAnimalsBuilderList() {
        return getAnimalsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          Animal, Animal.Builder, AnimalOrBuilder>
          getAnimalsFieldBuilder() {
        if (animalsBuilder_ == null) {
          animalsBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              Animal, Animal.Builder, AnimalOrBuilder>(
                  animals_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          animals_ = null;
        }
        return animalsBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:Zoo)
    }
    
    static {
      defaultInstance = new Zoo(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:Zoo)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Memo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Memo_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Description_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Description_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Animal_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Animal_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Zoo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Zoo_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n,src/perftestapp/model/protobuf/serperf" +
      ".proto\"$\n\004Memo\022\r\n\005lines\030\001 \003(\t\022\r\n\005count\030\002" +
      " \002(\005\"C\n\013Description\022\014\n\004note\030\001 \002(\t\022\021\n\ttim" +
      "estamp\030\002 \002(\003\022\023\n\004memo\030\003 \002(\0132\005.Memo\"S\n\006Ani" +
      "mal\022\n\n\002id\030\001 \002(\003\022\014\n\004name\030\002 \002(\t\022!\n\013descrip" +
      "tion\030\003 \002(\0132\014.Description\022\014\n\004type\030\004 \002(\005\"-" +
      "\n\003Zoo\022\014\n\004name\030\001 \002(\t\022\030\n\007animals\030\002 \003(\0132\007.A" +
      "nimalB \n\032perftestapp.model.protobufB\002Pb"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Memo_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Memo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Memo_descriptor,
              new String[] { "Lines", "Count", },
              Memo.class,
              Memo.Builder.class);
          internal_static_Description_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_Description_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Description_descriptor,
              new String[] { "Note", "Timestamp", "Memo", },
              Description.class,
              Description.Builder.class);
          internal_static_Animal_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_Animal_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Animal_descriptor,
              new String[] { "Id", "Name", "Description", "Type", },
              Animal.class,
              Animal.Builder.class);
          internal_static_Zoo_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_Zoo_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Zoo_descriptor,
              new String[] { "Name", "Animals", },
              Zoo.class,
              Zoo.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
